export const sampleSongs = [
  {
    id: 1,
    title: 'Shin Takata Jima',
    album: 'Music Album',
    artist: 'Sakanaction',
    genre: 'Dance / Indie',
    duration: '4:12',
    rating: 4.6,
    total_copies: 20,
    available_copies: 10,
    description:
      'An energetic and atmospheric track blending indie rock with electronic dance influences, creating a distinct modern Japanese sound.',
    color: '#1c1f40',
    imageUrl: 'https://placehold.co/400x600.png',
    audioUrl: '/sample-video.mp4?updatedAt=1722593504152',
    lyrics:
      'A poetic blend of nostalgia and motion, reflecting the harmony between city lights and ocean waves.',
    tags: ['Japanese', 'indie', 'electronic', 'energetic'],
  },
  {
    id: 2,
    title: 'Midnight Breeze',
    album: 'City Nights',
    artist: 'Luna Wave',
    genre: 'Synthwave / Chill',
    duration: '3:58',
    rating: 4.8,
    total_copies: 15,
    available_copies: 7,
    description:
      'A smooth, neon-lit synthwave track that evokes the calm and mystery of a quiet midnight drive through the city.',
    color: '#0d1b2a',
    imageUrl: 'https://placehold.co/400x600.png',
    audioUrl: '/sample-video.mp4',
    lyrics:
      'Under city lights we fade, our echoes lost in time — chasing dreams through endless night.',
    tags: ['synthwave', 'retro', 'calm', 'night'],
  },
  {
    id: 3,
    title: 'Golden Horizon',
    album: 'Echoes of Dawn',
    artist: 'Aurora Sky',
    genre: 'Ambient / Instrumental',
    duration: '5:05',
    rating: 4.5,
    total_copies: 25,
    available_copies: 18,
    description:
      'A calming instrumental that paints a picture of sunrise over the mountains with lush ambient textures and warm tones.',
    color: '#d97706',
    imageUrl: 'https://placehold.co/400x600.png',
    audioUrl: '/sample-video.mp4',
    lyrics: '',
    tags: ['ambient', 'instrumental', 'calm', 'nature'],
  },
  {
    id: 4,
    title: 'Parallel Hearts',
    album: 'Future Pulse',
    artist: 'Kyra Nova',
    genre: 'Pop / Electronic',
    duration: '3:42',
    rating: 4.3,
    total_copies: 30,
    available_copies: 20,
    description:
      'A catchy electronic pop anthem about two souls moving through parallel paths, destined to meet under the digital glow.',
    color: '#9333ea',
    imageUrl: 'https://placehold.co/400x600.png',
    audioUrl: '/sample-video.mp4',
    lyrics: 'We run in sync, two lines apart, meeting in echoes of electric hearts.',
    tags: ['pop', 'electronic', 'female-vocalist', 'upbeat'],
  },
  {
    id: 5,
    title: 'Crimson Trail',
    album: 'Lost Path',
    artist: 'The Wanderers',
    genre: 'Rock / Alternative',
    duration: '4:50',
    rating: 4.1,
    total_copies: 18,
    available_copies: 8,
    description:
      'An intense guitar-driven track exploring the restless energy of breaking free and finding your own path.',
    color: '#991b1b',
    imageUrl: 'https://placehold.co/400x600.png',
    audioUrl: '/sample-video.mp4',
    lyrics:
      'Running through the crimson haze, chasing voices in the rain — I won’t turn back again.',
    tags: ['rock', 'alternative', 'energetic', 'guitar'],
  },
  {
    id: 6,
    title: 'Fading Echoes',
    album: 'Reflections',
    artist: 'Eon Drift',
    genre: 'Lo-fi / Chillhop',
    duration: '2:57',
    rating: 4.9,
    total_copies: 40,
    available_copies: 25,
    description:
      'Soft lo-fi beats layered with gentle piano tones and vinyl textures — the perfect background track for relaxation or study.',
    color: '#4b5563',
    imageUrl: 'https://placehold.co/400x600.png',
    audioUrl: '/sample-video.mp4',
    lyrics: '',
    tags: ['lofi', 'study', 'chill', 'instrumental'],
  },
  {
    id: 7,
    title: 'Ocean Between Us',
    album: 'Blue Horizon',
    artist: 'Mira Solis',
    genre: 'Acoustic / Folk',
    duration: '4:18',
    rating: 4.4,
    total_copies: 22,
    available_copies: 11,
    description:
      'A heartfelt acoustic ballad about distance and connection, carried by warm vocals and gentle guitar melodies.',
    color: '#2563eb',
    imageUrl: 'https://placehold.co/400x600.png',
    audioUrl: '/sample-video.mp4',
    lyrics: 'Across the tides your voice remains, whispering through the salt and rain.',
    tags: ['acoustic', 'folk', 'emotional', 'vocal'],
  },
];
