export const FIELD_NAMES = {
  username: "User name",
  email: "Email",
  password: "Password",
  confirmPassword: "Confirm Password",
};

export const FIELD_TYPES = {
  username: "text",
  email: "email",
  password: "password",
  confirmPassword: "password",
};

export const inspirationTags = [
  "Hip-Hop/Rap",
  "Rock",
  "EDM",
  "Pop",
  "Country",
  "R&B",
  "Jazz",
  "Classical",
  "Metal",
  "Folk",
  "Blues",
  "Soul",
  "Punk",
];

export const sampleSongs = [
  {
    id: "1",
    title: "Yoru no Odoriko",
    audioUrl: "/sample-video.mp4?updatedAt=1722593504152",
    imageUrl: "https://placehold.co/400x600.png",
    creator: "Sakanaction",
    description:
      "An energetic and atmospheric track blending indie rock with electronic dance influences, creating a distinct modern Japanese sound.",
    color: "#D79922",
    lyrics:
      "A poetic blend of nostalgia and motion, reflecting the harmony between city lights and ocean waves.",
    status: "available",
    isAISong: false,
    instrumental: false,
    duration: 252, // 4:12 in seconds
    published: true,
    listenCount: 1250,
    likes: [],
    playlists: [],
    comments: [],
    tags: ["Japanese", "indie", "electronic", "energetic"],
    createdAt: "2023-01-15T10:00:00Z",
    updatedAt: "2023-01-15T10:00:00Z",
  },
  {
    id: "2",
    title: "Midnight Breeze",
    audioUrl: "/sample-video.mp4",
    imageUrl: "https://placehold.co/400x600.png",
    creator: "Luna Wave",
    description:
      "A smooth, neon-lit synthwave track that evokes the calm and mystery of a quiet midnight drive through the city.",
    color: "#0d1b2a",
    lyrics:
      "Under city lights we fade, our echoes lost in time — chasing dreams through endless night.",
    status: "available",
    isAISong: false,
    instrumental: false,
    duration: 238, // 3:58 in seconds
    published: true,
    listenCount: 980,
    likes: [],
    playlists: [],
    comments: [],
    tags: ["synthwave", "retro", "calm", "night"],
    createdAt: "2023-02-10T08:30:00Z",
    updatedAt: "2023-02-10T08:30:00Z",
  },
  {
    id: "3",
    title: "Golden Horizon",
    audioUrl: "/sample-video.mp4",
    imageUrl: "https://placehold.co/400x600.png",
    creator: "Aurora Sky",
    description:
      "A calming instrumental that paints a picture of sunrise over the mountains with lush ambient textures and warm tones.",
    color: "#d97706",
    lyrics: "",
    status: "available",
    isAISong: false,
    instrumental: true,
    duration: 305, // 5:05 in seconds
    published: true,
    listenCount: 670,
    likes: [],
    playlists: [],
    comments: [],
    tags: ["ambient", "instrumental", "calm", "nature"],
    createdAt: "2023-03-05T12:15:00Z",
    updatedAt: "2023-03-05T12:15:00Z",
  },
  {
    id: "4",
    title: "Parallel Hearts",
    audioUrl: "/sample-video.mp4",
    imageUrl: "https://placehold.co/400x600.png",
    creator: "Kyra Nova",
    description:
      "A catchy electronic pop anthem about two souls moving through parallel paths, destined to meet under the digital glow.",
    color: "#9333ea",
    lyrics:
      "We run in sync, two lines apart, meeting in echoes of electric hearts.",
    status: "available",
    isAISong: false,
    instrumental: false,
    duration: 222, // 3:42 in seconds
    published: true,
    listenCount: 1450,
    likes: [],
    playlists: [],
    comments: [],
    tags: ["pop", "electronic", "female-vocalist", "upbeat"],
    createdAt: "2023-04-01T09:45:00Z",
    updatedAt: "2023-04-01T09:45:00Z",
  },
  {
    id: "5",
    title: "Crimson Trail",
    audioUrl: "/sample-video.mp4",
    imageUrl: "https://placehold.co/400x600.png",
    creator: "The Wanderers",
    description:
      "An intense guitar-driven track exploring the restless energy of breaking free and finding your own path.",
    color: "#991b1b",
    lyrics:
      "Running through the crimson haze, chasing voices in the rain — I won’t turn back again.",
    status: "available",
    isAISong: false,
    instrumental: false,
    duration: 290, // 4:50 in seconds
    published: true,
    listenCount: 860,
    likes: [],
    playlists: [],
    comments: [],
    tags: ["rock", "alternative", "energetic", "guitar"],
    createdAt: "2023-05-12T11:20:00Z",
    updatedAt: "2023-05-12T11:20:00Z",
  },
  {
    id: "6",
    title: "Fading Echoes",
    audioUrl: "/sample-video.mp4",
    imageUrl: "https://placehold.co/400x600.png",
    creator: "Eon Drift",
    description:
      "Soft lo-fi beats layered with gentle piano tones and vinyl textures — the perfect background track for relaxation or study.",
    color: "#4b5563",
    lyrics: "",
    status: "available",
    isAISong: false,
    instrumental: true,
    duration: 177, // 2:57 in seconds
    published: true,
    listenCount: 2300,
    likes: [],
    playlists: [],
    comments: [],
    tags: ["lofi", "study", "chill", "instrumental"],
    createdAt: "2023-06-08T15:00:00Z",
    updatedAt: "2023-06-08T15:00:00Z",
  },
  {
    id: "7",
    title: "Ocean Between Us",
    audioUrl: "/sample-video.mp4",
    imageUrl: "https://placehold.co/400x600.png",
    creator: "Mira Solis",
    description:
      "A heartfelt acoustic ballad about distance and connection, carried by warm vocals and gentle guitar melodies.",
    color: "#2563eb",
    lyrics:
      "Across the tides your voice remains, whispering through the salt and rain.",
    status: "available",
    isAISong: false,
    instrumental: false,
    duration: 258, // 4:18 in seconds
    published: true,
    listenCount: 910,
    likes: [],
    playlists: [],
    comments: [],
    tags: ["acoustic", "folk", "emotional", "vocal"],
    createdAt: "2023-07-03T14:40:00Z",
    updatedAt: "2023-07-03T14:40:00Z",
  },
];
